name: python-semantic-release
description: python-semantic-release

inputs:
  github_token:
    description: GitHub token for authentication
    required: true
    default: ""

  verbosity:
    description: Verbosity level for semantic-release actions
    required: false
    default: "1"

  config_file:
    description: Configuration file for semantic-release
    required: false
    default: "releaserc.toml"

  git_committer_name:
    description: Name for git committer
    required: false
    default: "github-actions"

  git_committer_email:
    description: Email for git committer
    required: false
    default: "actions@users.noreply.github.com"

runs:
  using: composite
  steps:
    # SRC: https://python-semantic-release.readthedocs.io/en/latest/configuration/automatic-releases/github-actions.html#common-workflow-example
    - name: semantic-release version
      id: semantic-release-version
      # Adjust tag with desired version if applicable.
      uses: python-semantic-release/python-semantic-release@v10.5.2
      with:
        verbosity: ${{ inputs.verbosity }}
        config_file: ${{ inputs.config_file }}
        github_token: ${{ inputs.github_token }}
        # TODO move to releaserc.toml
        git_committer_name: ${{ inputs.git_committer_name }}
        git_committer_email: ${{ inputs.git_committer_email }}

    - name: semantic-release publish
      uses: python-semantic-release/publish-action@v10.5.2
      if: steps.semantic-release-version.outputs.released == 'true'
      with:
        verbosity: ${{ inputs.verbosity }}
        config_file: ${{ inputs.config_file }}
        github_token: ${{ inputs.github_token }}
        tag: ${{ steps.semantic-release-version.outputs.tag }}
