name: Test actions/setup

on:
  push:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/setup

  matrix:
    needs: default
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          # - "3.13" # Already tested from .python-version file
          # - "3.14" # TODO: Uncomment when available

        architecture:
          - x64

        OS:
          - ubuntu-latest
          - windows-latest
          - macOS-latest

    name: "python@${{ matrix.python-version }} @ ${{ matrix.OS }}@${{ matrix.architecture }}"
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main

      - uses: ./.github/actions/setup
        with:
          python-version-file: ./assets/python-version-file/v${{ matrix.python-version }}/.python-version
          architecture: ${{ matrix.architecture }}
