name: Test actions/setup-python

on:
  push:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  default:
    runs-on: ubuntu-latest

    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main

      - uses: ./.github/actions/setup-python

  matrix:
    needs: default
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          # - "3.14" # TODO: Uncomment when available

        architecture:
          - x64

        OS:
          - ubuntu-latest
          - windows-latest
          - macOS-latest

    name: "python@${{ matrix.python-version }} @ ${{ matrix.OS }}@${{ matrix.architecture }}"
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main

      - uses: ./.github/actions/setup-python
        with:
          python-version-file: v${{ matrix.python-version }}/.python-version
          architecture: ${{ matrix.architecture }}
